CREATE TABLE UZYTKOWNIK 
(login VARCHAR(16) NOT NULL,
	CONSTRAINT PK_UZYTKOWNIK PRIMARY KEY (login),
imie NVARCHAR(20) NOT NULL,
nazwisko NVARCHAR(30) NOT NULL,
haslo CHAR(32) NOT NULL,
rodzaj_konta ENUM NOT NULL,
email VARCHAR(32)
);

CREATE TABLE UCZEN 
(uczen_ID INT(3) NOT NULL,
	CONSTRAINT PK_UCZEN PRIMARY KEY (uczen_ID),
pesel CHAR(11) NOT NULL,
adres_ID INT(3) NOT NULL,
	CONSTRAINT FK_ADRES,
		FOREIGN KEY (adres_ID)
		REFERENCES ADRES(adres_id),
klasa_ID INT(2) NOT NULL,
	CONSTRAINT FK_KLASA,
		FOREIGN KEY (klasa_ID),
		REFERENCES KLASA(klasa_id),
opiekunowie_ID INT(3) NOT NULL,
	CONSTRAINT FK_OPIEKUNOWIE,
		FOREIGN KEY (opiekunowie_ID),
		REFERENCES OPIEKUNOWIE(opiekunowie_ID),
login VARCHAR(16) NOT NULL,
	CONSTRAINT FK_UZYTKOWNIK,
		FOREIGN KEY (login),
		REFERENCES UZYTKOWNIK(login)
);

CREATE TABLE RODZIC 
(rodzic_ID INT(3) NOT NULL,
	CONSTRAINT PK_RODZIC PRIMARY KEY (rodzic_ID),
nr_telefonu VARCHAR(12) NOT NULL,
opiekunowie_ID INT(3) NOT NULL,
login VARCHAR(16) NOT NULL,
	CONSTRAINT FK_UZYTKOWNIK,
		FOREIGN KEY (login),
		REFERENCES UZYTKOWNIK(login)
);

CREATE TABLE OPIEKUNOWIE 
(opiekunowie_ID INT(3) NOT NULL,
	CONSTRAINT FK_OPIEKUNOWIE,
		FOREIGN KEY (opiekunowie_ID),
		REFERENCES OPIEKUNOWIE(opiekunowie_ID)
);

CREATE TABLE ADRES
(adres_ID INT(3) NOT NULL,
	CONSTRAINT PK_ADRES PRIMARY KEY (adres_ID),
ulice_miejscowosci_ID INT(6) NOT NULL,
	CONSTRAINT FK_ULICE_MIEJSCOWOSCI,
		FOREIGN KEY (ulice_miejscowosci_ID),
		REFERENCES ULICE_MIEJSCOWOSCI(ulice_miejscowosci_ID),
nr_domu VARCHAR(5) NOT NULL,
nr_mieszkania VARCHAR(4) NOT NULL
kod INT(5) NOT NULL
);

CREATE TABLE MIEJSCOWOSC
(mijscowosc_ID INT(3) NOT NULL,
	CONSTRAINT PK_KEY PRIMARY KEY (mijscowosc_ID),
nazwa NVARCHAR(30)
);

CREATE TABLE ULICE_MIEJSCOWOSCI
(ulice_miejscowosci_ID INT(6) NOT NULL,
	CONSTRAINT PK_ULICE_MIEJSCOWOSCI PRIMARY KEY (ulice_miejscowosci_ID),
mijscowosc_ID INT(3) NOT NULL,
	CONSTRAINT FK_MIEJSCOWOSC,
		FOREIGN KEY (mijscowosc_ID),
		REFERENCES MIEJSCOWOSC(mijscowosc_ID),		
ulica_ID INT(3) NOT NULL,
	CONSTRAINT FK_ULICA,
		FOREIGN KEY (ulica_ID),
		REFERENCES ULICA(ulica_ID),
);

CREATE TABLE ULICA 
(ulica_ID INT(3) NOT NULL,
	CONSTRAINT PK_ULICA PRIMARY KEY (ulica_ID),
nazwa NVARCHAR(30) NOT NULL
);

CREATE TABLE KLASA 
(klasa_ID INT (2) NOT NULL,
	CONSTRAINT PK_KLASA PRIMARY KEY (klasa_ID),
oddzial CHAR(2) NOT NULL,
wychowawca_ID INT(2) NOT NULL,
	CONSTRAINT FK_NAUCZYCIEL,
		FOREIGN KEY (nauczyciel_ID),
		REFERENCES NAUCZYCIEL(nauczyciel_ID)
);

CREATE TABLE PRZEDMIOT 
(przedmiot_ID INT(2) NOT NULL,
	CONSTRAINT PK_PRZEDMIOT PRIMARY KEY (przedmiot_ID),
nazwa NVARCHAR(32) NOT NULL
);

CREATE TABLE NAUCZYCIEL_PRZEDMIOTU
(nauczyciel_przedmiotu_ID INT(3) NOT NULL,
	CONSTRAINT PK_NAUCZYCIEL_PRZEDMIOTU PRIMARY KEY(nauczyciel_przedmiotu_ID),
nauczyciel_ID INT(2) NOT NULL, 
	CONSTRAINT FK_NAUCZYCIEL,
		FOREIGN KEY (nauczyciel_ID),
		REFERENCES NAUCZYCIEL(nauczyciel_ID),
przedmiot_ID INT(2) NOT NULL,
	CONSTRAINT FK_PRZEDMIOT,
		FOREIGN KEY (przedmiot_ID),
		REFERENCES PRZEDMIOT(przedmiot_ID)
);

CREATE TABLE OCENA
(ocena_ID INT(6) NOT NULL
	CONSTRAINT PK_OCENA PRIMARY KEY(ocena_ID),
stopien ENUM NOT NULL,
waga INT(1) NOT NULL,
opis NVARCHAR(100),
data_wystawienia DATE NOT NULL,
uczen_ID INT(3) NOT NULL,
	CONSTRAINT FK_UCZEN,
		FOREIGN KEY (uczen_ID),
		REFERENCES UCZEN(uczen_ID),
nauczyciel_przedmiotu_ID NOT NULL,
	CONSTRAINT FK_NAUCZYCIEL_PRZEDMIOTU,
		FOREIGN KEY (nauczyciel_przedmiotu_ID),
		REFERENCES NAUCZYCIEL_PRZEDMIOTU(nauczyciel_przedmiotu_ID)
);

CREATE TABLE CZAS_LEKCJI
(czas_lekcji_ID INT(5) NOT NULL,
	CONSTRAINT PK_CZAS_LEKCJI PRIMARY KEY(czas_lekcji_ID),	
data_lekcji DATE NOT NULL,
godz_rozpoczecia TIME NOT NULL,
godz_zakonczenia TIME NOT NULL
);

CREATE TABLE LEKCJA 
(lekcja_ID INT(5) NOT NULL,
	CONSTRAINT PK_LEKCJA PRIMARY KEY(lekcja_ID),
grupa_lekcji_ID INT(3) NOT NULL,
	CONSTRAINT FK_GRUPA_LEKCJI,
		FOREIGN KEY (grupa_lekcji_ID),
		REFERENCES GRUPA_LEKCJI(grupa_lekcji_ID),
temat NVARCHAR(20) NOT NULL,
czas_lekcji_ID INT(5) NOT NULL,
	CONSTRAINT FK_CZAS_LEKCJI,
		FOREIGN KEY (czas_lekcji_ID),
		REFERENCES CZAS_LEKCJI(czas_lekcji_ID),
sala INT(2)
);

CREATE TABLE OBECNOSC
(obecnosc_ID INT(7) NOT NULL,
	CONSTRAINT PK_OBECNOSC PRIMARY KEY(obecnosc_ID),
status ENUM NOT NULL,
uczen_ID INT(3) NOT NULL,
	CONSTRAINT FK_UCZEN,
		FOREIGN KEY (uczen_ID),
		REFERENCES UCZEN(uczen_ID),
lekcja_ID INT(5) NOT NULL,
	CONSTRAINT FK_LEKCJA,
		FOREIGN KEY (lekcja_ID),
		REFERENCES LEKCJA(lekcja_ID)
);

CREATE TABLE GRUPA_LEKCJI
(grupa_lekcji_ID INT(3) NOT NULL,
	CONSTRAINT PK_GRUPA_LEKCJI PRIMARY KEY(grupa_lekcji_ID),
nauczyciel_przedmiotu_ID NOT NULL,
	CONSTRAINT FK_NAUCZYCIEL_PRZEDMIOTU,
		FOREIGN KEY (nauczyciel_przedmiotu_ID),
		REFERENCES NAUCZYCIEL_PRZEDMIOTU(nauczyciel_przedmiotu_ID),
klasa_ID INT(2) NOT NULL,
	CONSTRAINT FK_KLASA,
		FOREIGN KEY (klasa_ID),
		REFERENCES KLASA(klasa_id)
);

CREATE TABLE NAUCZYCIEL
(nauczyciel_ID INT(2) NOT NULL,
	CONSTRAINT PK_NAUCZYCIEL PRIMARY KEY(nauczyciel_ID),
nr_telefonu INT(11),
czy_wychowawca ENUM NOT NULL,
login VARCHAR(16) NOT NULL,
	CONSTRAINT FK_UZYTKOWNIK,
		FOREIGN KEY (login),
		REFERENCES UZYTKOWNIK(login)
);


